### ISSUE TITLE
The effect of multiple \babelhyphenation is unclear; please specify.

### ISSUE THREAD

**Issue by PeterMuellerr** [latex3/babel#174]
The documentation says, “Multiple `\babelhyphenation`’s are allowed” but does not specify the effect of multiple `\babelhyphenation`s.  The way I read it, two commands `\babelhyphenation` produce no error. However, nothing more is implied.  In particular, what is the effect of `\babelhyphenation[L]{list1} \babelhyphenation[L]{list2}` for a language L? I can imagine four possibilities for the total effect:

1. `\babelhyphenation[L]{list1}`
2. `\babelhyphenation[L]{list2}`
3. `\babelhyphenation[L]{list1 list2}`
4. `\babelhyphenation[L]{list2 list1}`

Or does something else happen? Please specify it in the documentation.

**Comment by jbezos** [comment]
With the exception explained in the manual, it behaves in the same way as `\hyphenation`. In other words, several `\babelhyphenation`’s in a row are much like several `\hyphenation`’s in a row. Since the behaviour is not different, I didn't think I had to say it explicitly, but I’ll add it to the manual.

**Comment by PeterMuellerr** [comment]
@jbezos Thanks; please do!
