### ISSUE TITLE
Undefined control sequence in Greek month names

### ISSUE THREAD

**Issue by gmilde** [latex3/babel#232]
Testing the built-in Greek support with pdflatex, I came across an "! Undefined control sequence." error: `` \textdialytikatonos`` is a misspelling of the accent command ``\accdialytikatonos`` for the combinded dialytika and tonos accent.

Please change the month name definitions  in

    babel-el-polyton.ini:132:months.wide.5 = \textMu\textalpha\textdialytikatonos\textiota\textomicron\textupsilon
    babel-el.ini:136:months.wide.5 = \textMu\textalpha\textdialytikatonos\textiota\textomicron\textupsilon

The breathing (psili) in Αὐγούστου is on the wrong character in the licr def:

    - \accpsili\textAlpha\textupsilon\textgamma\textomicron\'\textupsilon\textsigma\texttau\textomicron\textupsilon
    + \textAlpha\textupsilon\textgamma\textomicron\acctonos\textupsilon\textsigma\texttau\textomicron\textupsilon

I did not check for more problems. It may be an idea to compare with the definitions in babel-greek.

In the long term, it would be good to reduce code duplication. How could I access the definitions in the "locale" files from "greek.ldf"?

**Comment by jbezos** [comment]
As to the duplication, it’s in my todo list, but they are (usually) harmless, and I much prefer the `ini` is based on the externally maintained `ldf` and not the other way around. In the `ini` files there are several duplicates, because `en` is the same as `en-US` (except the tag), but as I said this is harmless.
