### ISSUE TITLE
Active apostrophe prevents compilation with LuaTeX

### ISSUE THREAD

**Issue by wehro** [latex3/babel#27]
As soon as the apostrophe `'` is made active and is occurring in a math formula, the compilation with LuaTeX never ends.
```
\documentclass{article}
\usepackage{babel}
\makeatletter
\initiate@active@char{'}
\makeatother

\begin{document}
$f'(x)$
\end{document}
```
This concerns the languges `slovak`, `spanglish` (with `asc` modifier), and `catalan` (with `activeacute` option).

Is it possible to repair this?

**Comment by blefloch** [comment]
I tested with 2018 versions of LuaTeX and babel, things may have
changed.  Since the character ' is math active (in both pdfTeX and
LuaTeX), TeX uses its active definition, which eventually calls
\normal@char'.  In LuaTeX, babel defines \normal@char' to be just the
character ', which calls the active definition, hence the loop.  In
pdfTeX instead the same command is defined as

    \textormath {'}{\csname bbl@oridef@@'\endcsname }

which does not trigger a loop since in math mode the original active '
definition is used (it takes care of placing primes properly).


The difference may come from a test in \@initiate@active@char, namely

    \ifnum\mathcode `#2="8000

In pdfTeX this is the correct test for math active characters, while in
LuaTeX it seems the math active math code is different: something like

    \ifnum\mathcode `#2="1000000

(but one should really check the LuaTeX doc, as this kind of things
changes from time to time).

**Comment by wehro** [comment]
Thank you for your analysis. I could not find anything about active math in the LuaTeX manual, but the following patch fixes the problem for me (tested with TeX Live 2019). The code might be optimized removing the code duplication.
```
476,477c476,485
<     \ifnum\mathcode`#2="8000
<       \@namedef{normal@char#2}{%
---
>     \ifodd\bbl@engine % luatex
>       \ifnum\mathcode`#2="1000000
>         \@namedef{normal@char#2}{%
>           \textormath{#3}{\csname bbl@oridef@@#2\endcsname}}%
>       \else
>         \@namedef{normal@char#2}{#3}%
>       \fi
>     \else % non-luatex
>       \ifnum\mathcode`#2="8000
>         \@namedef{normal@char#2}{%
479,480c487,489
<     \else
<       \@namedef{normal@char#2}{#3}%
---
>       \else
>         \@namedef{normal@char#2}{#3}%
>       \fi
```

**Comment by jbezos** [comment]
And for me. I'll fix it in the next release.
