### ISSUE TITLE
xparse warning if a font is set twice for the main language.

### ISSUE THREAD

**Issue by u-fischer** [latex3/babel#52]
When compiling this document

~~~~
\documentclass[]{book}
\usepackage[english]{babel}
\babelfont{rm}{Latin Modern Roman}
\babelfont[english]{rm}{Latin Modern Roman}
\begin{document}
 abc
\end{document}
~~~~

one gets the warning 

~~~~
LaTeX3 Warning: The command '\rmfamily' was undefined but not the associated
(LaTeX3)        commands '\rmfamily code' and/or '\rmfamily defaults'. Maybe
(LaTeX3)        you tried using \let. This may lead to an infinite loop.
~~~~

Compiled with lualatex and LaTeX2e <2020-02-02> patch level 5.

**Comment by blefloch** [comment]
Presumably we should provide a way to undefine an xparse command?

**Comment by PhelypeOleinik** [comment]
This is probably not something new. This warning was probably there from
long ago, but it was being redirected until https://github.com/latex3/latex3/commit/9dace07c

**Comment by blefloch** [comment]
Another option is to store all of the code for a non-expandable xparse
command \foo in the command itself, rather than "\foo code" and "\foo
defaults".  The idea would then be to make calls to "\foo" start by
defining "\foo code" and "\foo defaults" before doing the rest of the work.

This shouldn't be too hard, but that part of the xparse code is slightly
hairy when it comes to sharing between the expandable and non-expandable
code paths.

For expandable commands we really have to have various helper macros.

**Comment by u-fischer** [comment]
@blefloch what I don't get is why xparse cares about \rmfamily at all. As far as I can see it hasn't been defined  with \NewDocumentCommand.

**Comment by PhelypeOleinik** [comment]
Perhaps `\<any>family` could just be defined with `\protected`, since none
of them take arguments anyway. In this case the overhead of using `xparse`
doesn't seem worth it...

**Comment by u-fischer** [comment]
babel seems to be basically do something like this:

~~~~
\documentclass[]{book}
\usepackage{fontspec}
\let\rmfamily\undefined
\newfontfamily\rmfamily{Latin Modern Roman}
\let\rmfamily\undefined
\newfontfamily\rmfamily{Latin Modern Roman}

\begin{document}
blub
\end{document}
~~~~

And the second \newfontfamily gives the warning. Why doesn't babel use `\renewfontfamily` instead?

**Comment by jbezos** [comment]
I'm still with PL3 (I had no time to upgrade) and the message is not shown. Unfortunately, I'm not sure if I'll have time to fix it before TeXLive 2020 :-(.

Apparently, it works as expected (ie, the family is (re)defined correctly). Can you confirm this point?

**Comment by PhelypeOleinik** [comment]
@jbezos Updating `xparse` only should show the warning. And the `xparse`
version that shows the warning didn't go to TL'19, so no problem.

And yes, it's working correctly. This issue already existed for quite some time,
but since commit https://github.com/latex3/latex3/commit/9dace07c, the warning was activated, thus
all the noise (sorry :-).

The `may lead to an infinite loop` warning is in case you do:
```latex
\let\OLDrmfamily\rmfamily
\RenewDocumentCommand\rmfamily{}
  { {\rmfamily hello} }
```
which is not the case, so it's okay.

**Comment by FrankMittelbach** [comment]
we may want to have an undefine for xparse commands (but that would be an latex3/exparse issue. 

However, what I find questionable here without having looked at the code is that \rmfamily is overwritten in the first place  (if @u-fischer's MWE  is a correct reduction of the problem) which is most likey messing up  the NFSS interfaces (also for unicode engines)

**Comment by u-fischer** [comment]
@FrankMittelbach I think it is a correct reduction regarding the warning, but \rmfamily has imho the correct definition after begin document, so either there is some grouping involved or it is reset in some other way. 

@jbezos I get no warning if I use `\renewfontfamily`.

**Comment by jbezos** [comment]
The code is somewhat tricky because when I wrote it there was no way (or I didn't find) in `fontspec` to retrieve the data I needed for `\babelfont` to work (maybe things have changed). I've just read the code and what it does is: unset `\rmfamily`, save `\rmfamily-space`, call `\newfontfamily` (which actually restores `\rmfamilly`), save the data I need, restore `\rmfamily-space`.

In order to fix `babel` I have to analize what's going on because `\babelfont` is not just a `\newfontfamily` in disguise - it not always defines the language (with a language it just _predefines_ it, so that the font is not loaded if the corresponding combination of locale/family is not used), and it's able to define new font families. Changes in a hurry are dangerous, even when apparently trivial (you never know).

**Comment by FrankMittelbach** [comment]
Am 07.03.20 um 08:33 schrieb Javier Bezos:
> In order to fix |babel| I have to analize what's going on because 
> |\babelfont| is not just a |\newfontfamily| in disguise - it not always 
> defines the language (with a language it just /predefines/ it, so that 
> the font is not loaded if the corresponding combination of locale/family 
> is not used), and it's able to define new font families. Changes in a 
> hurry are dangerous, even when apparently trivial (you never know).

I may be mistaken and it may not help in your case, but we now have 
hooks inside \rmfamily and friends, e.g. \@rmfamilyhook  \@sffamilyhook 
\@ttfamilyhook and \@defaultfamilyhook in which one can place code to be 
run whenever \rmfamily etc is called to add additional actions to be 
carried out.

And agreed, I'm not suggesting to make rash changes, I was just 
observing that overwriting \rmfamily might not be the best solution (if 
that is what happens).

**Comment by jbezos** [comment]
@FrankMittelbach Thank you for pointing this out. I'm not sure yet, but they could be useful.
