### ISSUE TITLE
Ampersand \& turns "invalid in math mode" if greek option is used

### ISSUE THREAD

**Issue by MdAyquassar** [latex3/babel#53]
Running `pdflatex` on the input
```
\documentclass{article}
\usepackage[greek]{babel}
\begin{document}
\(\&\)
\end{document}
```
prints the following to the log and to tty:
> LaTeX Warning: Command \& invalid in math mode on input line 4.

But, the ampersand is supposed to be used in both math and text modes, isn't it? 

The same problem persists if you retain the `greek` option but add (probably) any other language (try, say, `[greek,ngerman]` instead of `[greek]`).

The PDF output looks ok, though.

An up-to-date Ubuntu 19.10 stock TeXLive installation is used, which has (according to the log) pdfTeX 3.14159265-2.6-1.40.20, LaTeX2e 2018-12-01, article 2018/09/03 v1.4i, babel 3.32, and lgrenc.def 2015/12/07 v0.13.1.

Any bugfix? Thx in advance.

**Comment by FrankMittelbach** [comment]
Looks like `\&` was changed to be encoding specific. Simple fix:
```
\usepackage[greek]{babel}
\makeatletter
\DeclareRobustCommand\&{\ifmmode\ltx@amp \else \ensureascii\ltx@amp\fi}
\makeatother
```
Could be done a bit cleaner I guess

**Comment by MdAyquassar** [comment]
Thanks for a quick reply!
1. Since \ltx@amp doesn't seem to public interface, is your workaround supposed to be temporary until a new release of LaTeX and/or babel?
2. Would your solution generically work also in case the document is sometimes fed to `xelatex`/`lualatex` or should the solution be kept specific to `pdflatex` and `latex` compilers?

**Comment by FrankMittelbach** [comment]
Don't know, I'm not maintaining babel nor greek for babel. It is defined by the greek style for babel (or by babel, have't checked which). I would expect it also works in the Unicode engines, but I haven't checked.

**Comment by jbezos** [comment]
The maintainer of the Greek style for babel es Günter Milde. You should contact him (the e-mail is in `greek.ldf`). I guess this is just one of many changes to make a non-LICR encoding (LGR) work within LaTeX. If would switch to a Unicode engine (xetex, luatex) if it's an option.

**Comment by MdAyquassar** [comment]
Dear Günter:

First, let me thank you for being the maintainer of the greek style for babel and
for all the work you've done so far. Second, I wonder whether I could kindly
attract your attention to the bug report
https://github.com/latex3/babel/issues/53 . It refers to your work and, according
to Javier, you are probably the person that could provide a bugfix.

Thank you in advance,
Md Ayquassar

  12.03.2020, 17:56, Javier Bezos <notifications@github.com>


  The maintainer of the Greek style for babel es Günter Milde. You should
  contact him (the e-mail is in greek.ldf). I guess this is just one of many
  changes to make a non-LICR encoding (LGR) work within LaTeX. If would switch
  to a Unicode engine (xetex, luatex) if it's an option.

**Comment by FrankMittelbach** [comment]
I have no idea what microtype does so that soul thinks that executing \& has a possible hyphen inside, but debugging soul or microtype would be rather difficult and I don't have enough time to solvethat puzzle.   So following the advice of soul:
```
\DeclareRobustCommand\&{\ifmmode\ltx@amp \else \mbox{\ensureascii\ltx@amp}\fi}
```

But this isn't really the right thing to do, it looks as if microtype causes a problem when there is a local encoding change to T1 or OT1 inside \hl, should be reported to Robert I guess, perhaps he can see what is wrong.

Here is an example with \textsterling, the same really happened with \&
```
\documentclass{article}


\usepackage{microtype}
\usepackage{soul}

% this is the default for textsterling and it works
\DeclareTextCommandDefault{\textsterling}{\UseTextSymbol{TS1}{\textsterling}}
\DeclareTextSymbol\textsterling{TS1}{163}

% this one fails  also fails if I point to OT1
% the moment microtype is added

\DeclareTextCommandDefault{\textsterling}{\UseTextSymbol{T1}{\textsterling}}
\DeclareTextSymbol\textsterling{T1}{191}


\begin{document}

 \pounds

\hl{a b \pounds{} c}

\end{document}
```

**Comment by MdAyquassar** [comment]
I've just made Robert aware of the issue you reported. Since the new issue doesn't involve babel, how about a new post at SE or latex.org for this? (Btw., my workaround of the problem induced by your original definition of \& was replacing the occurrence of `\hl{some text \& some other text}` by `\hl{some text and some other text}`, and I don't feel I need more bugfixing beyond this as of now.) In any case, thanks for looking into this. I'm afraid that soul (even with soulutf8) needs a rewrite from scratch anyway.

**Comment by FrankMittelbach** [comment]
neither soul nor microtype are maintained by us so the problem doesn't belong on latex-project.org or our github presence. My second suggestion does work though or explicitly doing
`\hl{abc \mbox{\&} xyz}`  would work too. `\&`should work in math so greek would need some fixing (implemented just like `\pounds` is really but again that is not core babel but a different maintainer. But that would fail stil in soul because of the issue with microtype. I couldn't see what the cause was, but perhaps Robert does.

**Comment by MdAyquassar** [comment]
> the problem doesn't belong on latex-project.org or our github presence

I fully agree.

**Comment by schlcht** [comment]
(phew, debugging soul is always such a blast ...)

The problem with regards to `microtype` is the font change. `soul` typesets its text twice: first in a vbox with a width of 1sp to get the single syllables (similar to `\showhyphens`), and then later again in an hbox, whose width is compared to that of the (split-up) vbox. Because of the font change, the text will not be typeset in the tt font that `soul` normally uses internally, but in a font that `microtype` gets to see. This alone is not the problem, but rather that font expansion will be applied differently in the two cases: Inside the vbox (case 1) the font will be shrunk to the maximum, while, by design, there never is any expansion in an hbox (case 2) -- this results in a mismatch of the widths which will finally make `soul` stumble. 

So, what I could do in `microtype` is disable font expansion for the first case (the vbox): 

```
\makeatletter
\let\MT@SOUL@doword\SOUL@doword
\def\SOUL@doword{\pdfadjustspacing=0 \MT@SOUL@doword}
\makeatother
```

which would at least solve the problem for `\&` or `\pounds`. 

But of course, `soul` remains awfully fragile -- even `\def\pounds{Pounding}` will fail, with or without `microtype` ...

**Comment by MdAyquassar** [comment]
Robert, thanks for looking into this!
@FrankMittelbach , @schlcht , @jbezos : To avoid cluttering this bugreport, let us move the discussion concerning `microtype` and `soul` to https://latex.org/forum/viewtopic.php?t=33292  and leave this bugreport to track the issue of `\&` in math mode when the greek module of babel is loaded.

**Comment by MdAyquassar** [comment]
@jbezos Have you received the file from Günter? (Several days ago, he replied to me with a bugfix, and I tested it.)

**Comment by jbezos** [comment]
@MdAyquassar No, I haven't, or at least I cannot find it.

**Comment by MdAyquassar** [comment]
Dear Javier:
Why have you closed the bug report then? Perhaps, you could wait until Günter (in
"Cc:") comes with a new greek.ldf. In my understanding, he has something to say
(at least I have seen a bug fix), but I would not like to speak instead of him.

Cheers,
Md Ayquassar

  22.03.2020, 15:10, Javier Bezos <notifications@github.com>


  @MdAyquassar No, I haven't, or at least I cannot find it.

**Comment by jbezos** [comment]
The error is not in babel, but in a package I'm not maintaining and I don't have to take any further action from my part.

**Comment by jbezos** [comment]
@MdAyquassar JFYI, I've noticed Günter has released the new version: https://ctan.org/pkg/babel-greek .

**Comment by MdAyquassar** [comment]
After you earlier message https://github.com/latex3/babel/issues/53#issuecomment-602505546, I don't have to continue any conversation with you here on this topic.
